[workspace]
members = [
	"syntax",
	"core",
	"context-processing",
	"expansion",
	"compaction",
	"serialization",
	"testing",
	"tests",
	"json-ld",
	"cli"
]

resolver = "2"

[workspace.package]
version = "0.15.1"
edition = "2021"
authors = ["Timothée Haudebourg <timothee@haudebourg.net>"]
categories = ["web-programming", "database", "data-structures"]
keywords = ["json-ld", "json", "semantic-web", "linked-data", "rdf"]
repository = "https://github.com/timothee-haudebourg/json-ld"
license = "MIT/Apache-2.0"

[workspace.dependencies]
json-ld = { path = "json-ld", version = "0.15.1" }
json-ld-syntax = { path = "syntax", version = "0.15.1" }
json-ld-core = { path = "core", version = "0.15.1" }
json-ld-context-processing = { path = "context-processing", version = "0.15.1" }
json-ld-expansion = { path = "expansion", version = "0.15.1" }
json-ld-compaction = { path = "compaction", version = "0.15.1" }
json-ld-serialization = { path = "serialization", version = "0.15.1" }
json-ld-testing = { path = "testing", version = "0.15.1" }
json-syntax = "0.12"
iref = "3.1.2"
static-iref = "3.0"
langtag = "0.4"
rdf-types = "0.22"
contextual = "0.1.4"
locspan = "0.8"
educe = "0.4.23"
futures = "0.3"
mown = "0.2.2"
hashbrown = "0.13.1"
smallvec = "1.10"
log = "0.4.17"
thiserror = "1.0.38"
serde = "1.0"
indexmap = "2.0"

iref-enum = "3.0"
async-std = "1.12"

linked-data = "0.1"